/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-09-02 00:28:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import dao.FruitDao;

public final class index_002danswer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>リクルート青果店</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("#container {\r\n");
      out.write("  width: 900px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  padding: 0px; border: 0px;\r\n");
      out.write("}\r\n");
      out.write("#header{width: 900px; height:100px; background: gray;}\r\n");
      out.write("#pagebody{width:900px; height:300px; margin: 0px; padding: 0px; border: 0px;}\r\n");
      out.write("#side { width:300px; height:300px; float:left; background: #0066cc; margin: 0px; padding: 0px; border: 0px;}\r\n");
      out.write("#contents { width:600px; height:300px; float:left; background: #ffcc00; margin: 0px; padding: 0px; border: 0px;}\r\n");
      out.write(".box { width:580px; height:30px; margin:10px; border:0; padding:0; background: green;}\r\n");
      out.write("#footer{ width: 900px; height:100px; clear:both; background: #009900; }\r\n");
      out.write(".child {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("    function demo01() {\r\n");
      out.write("    $(this).next().slideToggle(300);\r\n");
      out.write("    }\r\n");
      out.write("    $(\".toggle\").click(demo01);\r\n");
      out.write("\tfunction demo02() {\r\n");
      out.write("\t\t$(this).toggleClass(\"active\").next().slideToggle(300);\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\".switch .toggle\").click(demo02);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	FruitDao dao = new FruitDao();
	ArrayList<String> fruitList = dao.getFruitList();

      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("  <div id=\"header\">header</div>\r\n");
      out.write("  <div id=\"pagebody\">\r\n");
      out.write("    <div id=\"side\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a class=\"toggle menu\">商品別検索</a>\r\n");
      out.write("          <ul class=\"inner child child01\">\r\n");
      out.write("            <li>野菜検索</li>\r\n");
      out.write("            <li>果物検索</li>\r\n");
      out.write("            <li>デイリー品検索</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a class=\"toggle menu\">リクルート青果店について</a>\r\n");
      out.write("          <ul class=\"inner child child01\">\r\n");
      out.write("            <li>社長の言葉</li>\r\n");
      out.write("            <li>経営理念</li>\r\n");
      out.write("            <li>店舗リスト</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a class=\"toggle menu\" >株主向け情報</a>\r\n");
      out.write("          <ul class=\"inner child child01\">\r\n");
      out.write("            <li>売上の推移</li>\r\n");
      out.write("            <li>事業計画</li>\r\n");
      out.write("            <li>アニュアルレポート</li>\r\n");
      out.write("            <li>財務諸表</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"contents\">\r\n");
      out.write("      ");

	for(String name:fruitList){
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("      ");

	out.print(name);

      out.write("\r\n");
      out.write("      </div>\r\n");

		}

      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div><!-- contents end -->\r\n");
      out.write("  </div><!-- pagebody end -->\r\n");
      out.write("  <div id=\"footer\">footer</div>\r\n");
      out.write("</div><!-- container end -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
